import { Inter } from "next/font/google";

import { headerConfig } from "@/config";

import { Header } from "@/components/Header";
import "@/styles/globals.css";
import { Layout } from "@/components/Layout";

export const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}  text-neutral-800`}>
        <Header items={headerConfig} />

        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
