import { Inter } from "next/font/google";

import { socialLinks } from "@/config";

import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { Layout } from "@/components/Layout";

import "@/styles/globals.css";

export const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className} text-neutral-800`}>
        <Header />
        <Layout>
          <div className="pt-20">{children}</div>

          <div className="pt-10">
            <Footer items={socialLinks.socialMedia} />
          </div>
        </Layout>
      </body>
    </html>
  );
}
